
services:
  notebook:
    build: .
    volumes:
      - cd:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_LAB_ENABLE=yes
    command: "start.sh jupyter lab"

volumes:
  cd: