version: '3'
services:
  notebook:
    build: .
    volumes:
      - ./:/home/jovyan/work
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_LAB_ENABLE=yes
    command: 'start.sh jupyter lab'
    env_file:
      - C:/Users/toma/Documents/Foursquare_creds.txt